### ISSUE TITLE
Preprocessor error when title starts with resource

### ISSUE THREAD

**Issue by monika** [solidusjs/metadata#5]
This title causes a preprocessor error:

``` YAML
/photo-albums/{album_id}:
    title: "{{ resources.photo_album.name }} | Official Photos | Thomas Rhett"
```

This title does not:

``` YAML
/photo-albums/{album_id}:
    title: "a {{ resources.photo_album.name }} | Official Photos | Thomas Rhett"
```

The error

```
[2015-04-02T01:48:40.127Z] 16 Preprocessor Error:
TypeError: Cannot read property 'length' of null
    at /vagrant/thomasrhett.com/node_modules/jungle-solidus/node_modules/solidus-metadata/index.js:83:26
    at Array.sort (native)
    at addMetadata (/vagrant/thomasrhett.com/node_modules/jungle-solidus/node_modules/solidus-metadata/index.js:82:38)
    at module.exports (/vagrant/thomasrhett.com/node_modules/jungle-solidus/preprocessors/site.js:19:13)
    at module.exports (/vagrant/thomasrhett.com/preprocessors/jungle-solidus.js:4:13)
    at module.exports (/vagrant/thomasrhett.com/node_modules/solidus/lib/preprocessor_worker.js:4:15)
    at handle (/vagrant/thomasrhett.com/node_modules/solidus/node_modules/worker-farm/lib/child/index.js:37:8)
    at process.<anonymous> (/vagrant/thomasrhett.com/node_modules/solidus/node_modules/worker-farm/lib/child/index.js:43:3)
    at process.EventEmitter.emit (events.js:98:17)
    at handleMessage (child_process.js:318:10)
```

**Comment by pushred** [comment]
This is actually a problem with the YAML parsing, here's what that's looking like with your file on this site:

``` json
{
  "/*": {
    "title": "Thomas Rhett",
    "image": "/images/content/facebook.png"
  },
  "/": {
    "title": "Thomas Rhett"
  },
  "/photos/{album_id}": null,
  "title": "{{ resources.story.response.posts.title }} | Thomas Rhett",
  "/news/{id}": null
}
```

Basically the problem route wasn't seeing the value. The file looked okay on the surface, but on further inspection I saw you're using tabs versus spaces. Please check your editor's config, you'll want to be sure to use 2 spaces. YAML [requires spaces be used](http://yaml.org/spec/current.html#indentation%20space/), it's very strict in this in order to remove all the curly brace noise that's present in JSON.

I was able to reproduce this with and without some text at the beginning, not sure what was happening on your end. I can't reproduce any issues with variables at the beginning of strings in the module itself and I stepped through the code and didn't find anything.
